version: "3"

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    image: aleph-cuda-pymc3-conda:cuda-9-cudnn-7
    container_name: pymc3-cuda
    environment:
      CUDA_PATH: /usr/local/cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    ports:
      - 8888:8888
    volumes:
      - ../notebooks:/home/jupyter/work
      - ../.theanorc:/home/jupyter/.theanorc
