version: "3"

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    image: aleph-ykunisato-ccp-lab-j
    container_name: ccp-lab-j
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    ports:
      - 8888:8888
    volumes:
      - ../notebooks:/home/jovyan/work
      - ../.theanorc:/home/jovyan/.theanorc
