version: "3"

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    image: aleph-nouiz
    container_name: jupyter
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      PASSWORD: 1234
      USE_HTTPS: yes
    ports:
      - 8888:8888
    volumes:
      - ../notebooks:/home/jovyan/work/notebook/work
      - ../.theanorc:/home/jovyan/.theanorc
